version: '2'
services:
  app:
    container_name: fakeServer
    build: .
    command: go run main.go
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      REQUESTDIRECTORY: requests